/**
 * Web Share API Helper Functions
 * Enables native sharing of content to social media, messaging apps, email, etc.
 */

/**
 * Check if Web Share API is supported
 */
export function isWebShareSupported() {
  return 'share' in navigator;
}

/**
 * Check if files can be shared (Web Share API Level 2)
 */
export function canShareFiles() {
  return navigator.canShare && navigator.canShare({ files: [] });
}

/**
 * Generic share function
 * @param {Object} data - Share data (title, text, url, files)
 * @returns {Promise<boolean>} - Success status
 */
export async function share(data) {
  if (!isWebShareSupported()) {
    console.log('Web Share API not supported');
    return false;
  }

  try {
    // Validate data
    if (!data.title && !data.text && !data.url && !data.files) {
      throw new Error('Share data must include at least one of: title, text, url, or files');
    }

    // Check if files can be shared
    if (data.files && !canShareFiles()) {
      console.warn('File sharing not supported, sharing without files');
      delete data.files;
    }

    // Trigger native share dialog
    await navigator.share(data);

    console.log('Content shared successfully');
    return true;
  } catch (error) {
    if (error.name === 'AbortError') {
      console.log('Share cancelled by user');
      return false;
    } else {
      console.error('Error sharing:', error);
      return false;
    }
  }
}

/**
 * Share player statistics
 * @param {Object} playerData - Player data to share
 */
export async function sharePlayerStats(playerData) {
  const { name, stats, period } = playerData;

  const shareData = {
    title: `${name}'s Performance Stats`,
    text: `Check out ${name}'s performance for ${period || 'this period'}:

⚽ Goals: ${stats.goals || 0}
🎯 Assists: ${stats.assists || 0}
📊 Attendance: ${stats.attendance || 0}%
⭐ Rating: ${stats.rating || 'N/A'}

Track My Academy - Sports Academy Management`,
    url: window.location.origin + `/player/${playerData.id}`
  };

  return await share(shareData);
}

/**
 * Share performance report
 * @param {Object} reportData - Performance report data
 */
export async function sharePerformanceReport(reportData) {
  const { playerName, reportType, summary, url } = reportData;

  const shareData = {
    title: `${playerName} - ${reportType}`,
    text: `📊 Performance Report: ${reportType}

${summary}

Generated by Track My Academy`,
    url: url || window.location.href
  };

  return await share(shareData);
}

/**
 * Share training session
 * @param {Object} sessionData - Training session data
 */
export async function shareTrainingSession(sessionData) {
  const { name, date, time, location, description } = sessionData;

  const shareData = {
    title: `Training Session: ${name}`,
    text: `🏃 ${name}

📅 Date: ${date}
⏰ Time: ${time}
📍 Location: ${location}

${description || 'Join us for training!'}

Track My Academy`,
    url: window.location.href
  };

  return await share(shareData);
}

/**
 * Share achievement/goal
 * @param {Object} achievementData - Achievement data
 */
export async function shareAchievement(achievementData) {
  const { playerName, achievement, description, date } = achievementData;

  const shareData = {
    title: `🎉 ${playerName} - Achievement Unlocked!`,
    text: `🏆 ${achievement}

${description}

Achieved on: ${date}

Track My Academy - Celebrating Success!`,
    url: window.location.href
  };

  return await share(shareData);
}

/**
 * Share team roster
 * @param {Object} teamData - Team data
 */
export async function shareTeamRoster(teamData) {
  const { teamName, players, coach, season } = teamData;

  const playerList = players.map(p => `• ${p.name} - ${p.position}`).join('\n');

  const shareData = {
    title: `${teamName} - Team Roster`,
    text: `⚽ ${teamName} Roster
Season: ${season}

Coach: ${coach}

Players:
${playerList}

Track My Academy`,
    url: window.location.href
  };

  return await share(shareData);
}

/**
 * Share attendance record
 * @param {Object} attendanceData - Attendance data
 */
export async function shareAttendanceRecord(attendanceData) {
  const { playerName, period, attendanceRate, sessionsAttended, totalSessions } = attendanceData;

  const shareData = {
    title: `${playerName} - Attendance Record`,
    text: `📊 Attendance Record

Player: ${playerName}
Period: ${period}

✅ Attendance Rate: ${attendanceRate}%
📈 Sessions Attended: ${sessionsAttended}/${totalSessions}

Track My Academy`,
    url: window.location.href
  };

  return await share(shareData);
}

/**
 * Share invitation to join academy
 * @param {Object} inviteData - Invitation data
 */
export async function shareAcademyInvite(inviteData) {
  const { academyName, message, inviteCode } = inviteData;

  const shareData = {
    title: `Join ${academyName}!`,
    text: `⚽ You're invited to join ${academyName}!

${message || 'Come train with us and improve your athletic skills!'}

${inviteCode ? `Invite Code: ${inviteCode}` : ''}

Track My Academy - Sports Academy Management`,
    url: window.location.origin + (inviteCode ? `?invite=${inviteCode}` : '')
  };

  return await share(shareData);
}

/**
 * Share screenshot or image
 * @param {File|Blob} imageFile - Image file to share
 * @param {string} title - Share title
 * @param {string} text - Share text
 */
export async function shareImage(imageFile, title = 'Share Image', text = '') {
  if (!canShareFiles()) {
    console.error('File sharing not supported on this browser');
    return false;
  }

  try {
    const filesArray = [
      new File([imageFile], imageFile.name || 'image.png', {
        type: imageFile.type || 'image/png'
      })
    ];

    const shareData = {
      files: filesArray,
      title: title,
      text: text
    };

    // Check if this specific share is supported
    if (!navigator.canShare(shareData)) {
      throw new Error('This content cannot be shared');
    }

    return await share(shareData);
  } catch (error) {
    console.error('Error sharing image:', error);
    return false;
  }
}

/**
 * Share PDF report
 * @param {Blob} pdfBlob - PDF blob to share
 * @param {string} filename - PDF filename
 * @param {string} title - Share title
 */
export async function sharePDF(pdfBlob, filename = 'report.pdf', title = 'Performance Report') {
  if (!canShareFiles()) {
    console.error('File sharing not supported on this browser');
    return false;
  }

  try {
    const filesArray = [
      new File([pdfBlob], filename, { type: 'application/pdf' })
    ];

    const shareData = {
      files: filesArray,
      title: title,
      text: 'Generated by Track My Academy'
    };

    if (!navigator.canShare(shareData)) {
      throw new Error('PDF cannot be shared');
    }

    return await share(shareData);
  } catch (error) {
    console.error('Error sharing PDF:', error);
    return false;
  }
}

/**
 * Share current page
 * @param {string} customTitle - Optional custom title
 * @param {string} customText - Optional custom text
 */
export async function shareCurrentPage(customTitle = null, customText = null) {
  const shareData = {
    title: customTitle || document.title,
    text: customText || 'Check this out!',
    url: window.location.href
  };

  return await share(shareData);
}

/**
 * Copy to clipboard as fallback (for unsupported browsers)
 * @param {string} text - Text to copy
 */
export async function copyToClipboard(text) {
  try {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      console.log('Copied to clipboard');
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      console.log('Copied to clipboard (fallback)');
      return true;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Share with fallback to copy to clipboard
 * @param {Object} data - Share data
 */
export async function shareWithFallback(data) {
  // Try Web Share API first
  if (isWebShareSupported()) {
    const success = await share(data);
    if (success) return true;
  }

  // Fallback to copy to clipboard
  const textToCopy = `${data.title || ''}\n\n${data.text || ''}\n\n${data.url || ''}`.trim();
  const copied = await copyToClipboard(textToCopy);

  if (copied) {
    alert('Link copied to clipboard! You can now paste it anywhere.');
    return true;
  }

  return false;
}

/**
 * Get share data for social media platforms
 * @param {string} platform - Platform name (whatsapp, telegram, twitter, facebook)
 * @param {Object} data - Share data
 * @returns {string} - Platform-specific share URL
 */
export function getPlatformShareUrl(platform, data) {
  const text = encodeURIComponent(data.text || '');
  const url = encodeURIComponent(data.url || window.location.href);

  const urls = {
    whatsapp: `https://wa.me/?text=${text}%20${url}`,
    telegram: `https://t.me/share/url?url=${url}&text=${text}`,
    twitter: `https://twitter.com/intent/tweet?text=${text}&url=${url}`,
    facebook: `https://www.facebook.com/sharer/sharer.php?u=${url}`,
    linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${url}`,
    email: `mailto:?subject=${encodeURIComponent(data.title || '')}&body=${text}%20${url}`
  };

  return urls[platform.toLowerCase()] || null;
}

/**
 * Open platform-specific share dialog
 * @param {string} platform - Platform name
 * @param {Object} data - Share data
 */
export function shareOnPlatform(platform, data) {
  const shareUrl = getPlatformShareUrl(platform, data);

  if (shareUrl) {
    window.open(shareUrl, '_blank', 'width=600,height=400');
    return true;
  }

  return false;
}
